<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>VostokWarehouseMobile</RootNamespace>
    <ApplicationTitle>VOSTOK-WAREHOUSE</ApplicationTitle>
    <ApplicationId>com.vostok.warehouse</ApplicationId>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <MauiVersion>10.0.31</MauiVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    <PackageReference Include="LibVLCSharp.MAUI" Version="3.10.0" />
    <PackageReference Include="VideoLAN.LibVLC.Android" Version="3.10.0" />
  </ItemGroup>

</Project>
