name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install MAUI Android workload
        run: dotnet workload install maui-android

      - name: Restore
        run: dotnet restore VostokWarehouseMobile/VostokWarehouseMobile.csproj

      - name: Build Android APK
        run: >
          dotnet publish
          VostokWarehouseMobile/VostokWarehouseMobile.csproj
          -c Release
          -f net10.0-android
          -p:AndroidPackageFormat=apk
          --no-restore

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VOSTOK-WAREHOUSE-Android-APK
          path: VostokWarehouseMobile/bin/Release/net10.0-android/**/*.apk
